import { BottomNavigation, BottomNavigationAction, Box, Stack } from "@mui/material";
import RestoreIcon from '@mui/icons-material/Restore';
import FavoriteIcon from '@mui/icons-material/Favorite';
import LocationOnIcon from '@mui/icons-material/LocationOn';
import { useState } from "react";


function MuiBottomNav() {

    const [value, setvalue] = useState(null);
    const [color, setcolor] = useState('red')

    const handleChange = (e, v)=>{
        setvalue(v)
        
    }

    return ( 
        <Box className="Box1" sx={{width: '100vw', height: '100vh'}}>
            <Stack>
            {
                messageExamples.map(data=>{return (
                    <Box mx={2} my={3} display={'flex'} >
                        <Stack justifyContent={'center'}>
                            <Box>
                                <img style={{borderRadius: '100px', display: 'block'}} width={'50px'} height={'50px'} src={data.person}
                                alt="Profile" />
                            </Box>
                        </Stack>
                        <Stack px={2} textAlign={'left'}>
                            <Stack>{data.primary}</Stack>
                            <Stack color={'gray'}>{data.secondary}</Stack>
                        </Stack>
                    </Box>
                )})
            }
            </Stack>
            <BottomNavigation
                showLabels
                value={value}
                onChange={handleChange}
                sx={{position: "fixed", bottom: 0, width: '100vw', boxShadow: "0px 0px 5px -2px gray"}}
            >
                <BottomNavigationAction value='Recents' label='Recents' icon={<RestoreIcon />} />
                <BottomNavigationAction value='Favorites' label='Favorites' oncl icon={<FavoriteIcon sx={{color: value==='Favorites'?'#ff5c5c':'none'}} />} />
                <BottomNavigationAction value='Nearby' label='Nearby' icon={<LocationOnIcon />} />
            </BottomNavigation>
        </Box>
     );
}

export default MuiBottomNav;

const messageExamples = [
    {
      primary: 'Brunch this week?',
      secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      person: 'https://images.unsplash.com/photo-1598420651277-1ec76d1d2210?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MjB8ODM3NTA4MHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    },
    {
      primary: 'Birthday Gift',
      secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
      person: 'https://images.unsplash.com/photo-1598420651277-1ec76d1d2210?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MjB8ODM3NTA4MHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    },
    {
      primary: 'Recipe to try',
      secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
      person: 'https://images.unsplash.com/photo-1598420651277-1ec76d1d2210?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MjB8ODM3NTA4MHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    },
    {
      primary: 'Yes!',
      secondary: 'I have the tickets to the ReactConf for this year.',
      person: 'https://images.unsplash.com/photo-1598420651277-1ec76d1d2210?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MjB8ODM3NTA4MHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    },
    {
      primary: "Doctor's Appointment",
      secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
      person: 'https://images.unsplash.com/photo-1598420651277-1ec76d1d2210?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MjB8ODM3NTA4MHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    },
    {
      primary: 'Discussion',
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
      person: 'https://images.unsplash.com/photo-1598420651277-1ec76d1d2210?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MjB8ODM3NTA4MHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    },
    {
      primary: 'Summer BBQ',
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
      person: 'https://images.unsplash.com/photo-1598420651277-1ec76d1d2210?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MjB8ODM3NTA4MHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    },
  ];